version: '2'

services:
  web:
    environment:
      DEBUG: 'true'

    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        - VERSION=${VERSION}

    volumes:
      - ./modules:/usr/local/tomcat/.OpenMRS/modules:cached
      - ./owa:/usr/local/tomcat/.OpenMRS/owa:cached

      # Uncomment the next line to use Docker from inside the container. See https://aka.ms/vscode-remote/samples/docker-from-docker-compose for details.
      - /var/run/docker.sock:/var/run/docker.sock 

    network_mode: service:db
